variable "resource_group_name" {}
variable "location" {}
variable "automation_account_name" {}
variable "rubook_name" {}
variable "rubook_uri" {}
variable "schedule_name" {}
variable "schedule_frequency" {}
variable "schedule_start_date" {}
variable "schedule_start_time" {}
variable "vault_name" {}
variable "vault_resource_group_name" {}
