variable "location" {}
variable "resource_group_name" {}
variable "owner_tag" {}
variable "application_tag" {}
variable "environment_tag" {}
variable "storage_account_name" {}
variable "app_service_plan_name" {}
variable "service_plan_tier" {}
variable "service_plan_size" {}
variable "function_app_name" {}
