Param (
  [Parameter(Mandatory=$True)]
  [string]$subcriptionId
)
Write-Host ""
Write-Host "Subscription Migration Planner"
Write-Host "Version 1.0.0"
Write-Host ""


## Install and Import Az Module
Write-Host "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Importing module..."
Import-Module -Name Az -ErrorVariable ModuleError -ErrorAction SilentlyContinue
If ($ModuleError) {
    Write-Host "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Installing module..."
    Install-Module -Name Az
    Import-Module -Name Az
    Write-Host "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Successfully Installed module..."
}
Write-Host "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Successfully Imported module"
Write-Host ""

## Login to Azure Environment
Write-Host "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Logging in to Azure Account..."
Connect-AzAccount
Write-Host "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Successfully logged in to Azure Account"
Write-Host ""

#Select SubscriptionId
while ($subcriptionId.Length -le 35) {
    Write-Output "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Subscription Id not valid"
    $subcriptionId = Read-Host "Please input your Subscription Id"
}
Select-AzSubscription -SubscriptionId $subcriptionId
Write-Output "[$(get-date -Format "dd/mm/yy hh:mm:ss")] Subscription successfully selected"
Write-Output ""


## Move Support Hash Table
$supportList = @{
    "Microsoft.AAD/domainservices" = "FALSE"
    "Microsoft.AnalysisServices/servers"  = "TRUE"
    "Microsoft.ApiManagement/service" = "TRUE"
    "Microsoft.Authorization/policyassignments" = "FALSE"
    "Microsoft.Automation/automationaccounts" = "TRUE"
    "Microsoft.Automation/automationaccounts/configurations" = "TRUE"
    "Microsoft.Automation/automationaccounts/runbooks" = "TRUE"
    "Microsoft.AzureActiveDirectory/b2cdirectories" = "TRUE"
    "Microsoft.AzureStack/registrations" = "TRUE"
    "Microsoft.Backup/backupvault" = "FALSE"
    "Microsoft.Batch/batchaccounts" = "TRUE"
    "Microsoft.BatchAI/clusters" = "FALSE"
    "Microsoft.BatchAI/fileservers" = "FALSE"
    "Microsoft.BatchAI/jobs" = "FALSE"
    "Microsoft.BatchAI/workspaces" = "FALSE"
    "Microsoft.BingMaps/mapapis" = "FALSE"
    "Microsoft.BizTalkServices/biztalk" = "TRUE"
    "Microsoft.Blueprint/blueprintassignments" = "FALSE"
    "Microsoft.BotService/botservices" = "TRUE"
    "Microsoft.Cache/redis" = "TRUE"
    "Microsoft.Cdn/profiles" = "TRUE"
    "Microsoft.Cdn/profiles/endpoints" = "TRUE"
    "Microsoft.CertificateRegistration/certificateorders" = "TRUE"
    "Microsoft.CognitiveServices/accounts" = "TRUE"
    "Microsoft.Compute/availabilitysets" = "TRUE"
    "Microsoft.Compute/disks" = "TRUE"
    "Microsoft.Compute/galleries" = "FALSE"
    "Microsoft.Compute/galleries/images" = "FALSE"
    "Microsoft.Compute/galleries/images/versions" = "FALSE"
    "Microsoft.Compute/images" = "TRUE"
    "Microsoft.Compute/restorepointcollections" = "FALSE"
    "Microsoft.Compute/sharedvmimages" = "FALSE"
    "Microsoft.Compute/sharedvmimages/versions" = "FALSE"
    "Microsoft.Compute/snapshots" = "TRUE"
    "Microsoft.Compute/virtualmachines" = "TRUE"
    "Microsoft.Compute/virtualmachines/extensions" = "TRUE"
    "Microsoft.Compute/virtualmachinescalesets" = "TRUE"
    "Microsoft.Container/containergroups" = "FALSE"
    "Microsoft.ContainerInstance/containergroups" = "FALSE"
    "Microsoft.ContainerRegistry/registries" = "TRUE"
    "Microsoft.ContainerRegistry/registries/buildtasks" = "TRUE"
    "Microsoft.ContainerRegistry/registries/replications" = "FALSE"
    "Microsoft.ContainerRegistry/registries/webhooks" = "TRUE"
    "Microsoft.ContainerService/containerservices" = "FALSE"
    "Microsoft.ContainerService/managedclusters" = "FALSE"
    "Microsoft.ContentModerator/applications" = "TRUE"
    "Microsoft.CostManagement/connectors" = "TRUE"
    "Microsoft.CustomerInsights/hubs" = "TRUE"
    "Microsoft.DataBox/jobs" = "FALSE"
    "Microsoft.DataBoxEdge/databoxedgedevices" = "FALSE"
    "Microsoft.Databricks/workspaces" = "FALSE"
    "Microsoft.DataCatalog/catalogs" = "TRUE"
    "Microsoft.DataFactory/datafactories" = "TRUE"
    "Microsoft.DataFactory/factories" = "TRUE"
    "Microsoft.DataLake/datalakeaccounts" = "FALSE"
    "Microsoft.DataLakeAnalytics/accounts" = "TRUE"
    "Microsoft.DataLakeStore/accounts" = "TRUE"
    "Microsoft.DataMigration/services" = "FALSE"
    "Microsoft.DataMigration/services/projects" = "FALSE"
    "Microsoft.DataMigration/slots" = "FALSE"
    "Microsoft.DBforMariaDB/servers" = "FALSE"
    "Microsoft.DBforMySQL/servers" = "FALSE"
    "Microsoft.DBforPostgreSQL/servergroups" = "FALSE"
    "Microsoft.DBforPostgreSQL/servers" = "FALSE"
    "Microsoft.Devices/iothubs" = "TRUE"
    "Microsoft.Devices/provisioningservices" = "TRUE"
    "Microsoft.DevTestLab/labcenters" = "FALSE"
    "Microsoft.DevTestLab/labs" = "FALSE"
    "Microsoft.DevTestLab/labs/servicerunners" = "TRUE"
    "Microsoft.DevTestLab/labs/virtualmachines" = "FALSE"
    "Microsoft.DevTestLab/schedules" = "FALSE"
    "microsoft.dns/dnszones" = "FALSE"
    "microsoft.dns/dnszones/a" = "FALSE"
    "microsoft.dns/dnszones/aaaa" = "FALSE"
    "microsoft.dns/dnszones/cname" = "FALSE"
    "microsoft.dns/dnszones/mx" = "FALSE"
    "microsoft.dns/dnszones/ptr" = "FALSE"
    "microsoft.dns/dnszones/srv" = "FALSE"
    "microsoft.dns/dnszones/txt" = "FALSE"
    "microsoft.dns/trafficmanagerprofiles" = "FALSE"
    "Microsoft.DocumentDB/databaseaccounts" = "TRUE"
    "Microsoft.DomainRegistration/domains" = "TRUE"
    "Microsoft.EventGrid/topics" = "TRUE"
    "Microsoft.EventHub/clusters" = "TRUE"
    "Microsoft.EventHub/namespaces" = "TRUE"
    "Microsoft.HanaOnAzure/hanainstances" = "TRUE"
    "Microsoft.HardwareSecurityModules/dedicatedhsms" = "FALSE"
    "Microsoft.HDInsight/clusters" = "TRUE"
    "Microsoft.ImportExport/jobs" = "TRUE"
    "microsoft.insights/actiongroups" = "TRUE"
    "microsoft.insights/activitylogalerts" = "FALSE"
    "microsoft.insights/alertrules" = "TRUE"
    "microsoft.insights/autoscalesettings" = "TRUE"
    "microsoft.insights/components" = "TRUE"
    "microsoft.insights/metricalerts" = "FALSE"
    "microsoft.insights/scheduledqueryrules" = "TRUE"
    "microsoft.insights/webtests" = "TRUE"
    "microsoft.insights/workbooks" = "TRUE"
    "Microsoft.IoTCentral/iotapps" = "TRUE"
    "Microsoft.KeyVault/vaults" = "TRUE"
    "Microsoft.LabServices/labaccounts" = "TRUE"
    "Microsoft.LocationBasedServices/accounts" = "TRUE"
    "Microsoft.LocationServices/accounts" = "TRUE"
    "Microsoft.Logic/integrationaccounts" = "TRUE"
    "Microsoft.Logic/workflows" = "TRUE"
    "Microsoft.MachineLearning/commitmentplans" = "TRUE"
    "Microsoft.MachineLearning/webservices" = "FALSE"
    "Microsoft.MachineLearning/workspaces" = "TRUE"
    "Microsoft.MachineLearningCompute/operationalizationclusters" = "TRUE"
    "Microsoft.MachineLearningExperimentation/accounts" = "TRUE"
    "Microsoft.MachineLearningExperimentation/accounts/workspaces" = "TRUE"
    "Microsoft.MachineLearningExperimentation/accounts/workspaces/projects" = "TRUE"
    "Microsoft.MachineLearningExperimentation/teamaccounts" = "TRUE"
    "Microsoft.MachineLearningExperimentation/teamaccounts/workspaces" = "TRUE"
    "Microsoft.MachineLearningExperimentation/teamaccounts/workspaces/projects" = "TRUE"
    "Microsoft.MachineLearningModelManagement/accounts" = "TRUE"
    "Microsoft.ManagedIdentity/userassignedidentities" = "TRUE"
    "Microsoft.Maps/accounts" = "TRUE"
    "Microsoft.MarketplaceApps/classicdevservices" = "FALSE"
    "Microsoft.Media/mediaservices" = "TRUE"
    "Microsoft.Media/mediaservices/liveevents" = "TRUE"
    "Microsoft.Media/mediaservices/streamingendpoints" = "TRUE"
    "Microsoft.Migrate/projects" = "FALSE"
    "Microsoft.Network/applicationgateways" = "FALSE"
    "Microsoft.Network/applicationsecuritygroups" = "TRUE"
    "Microsoft.Network/connections" = "TRUE"
    "Microsoft.Network/ddosprotectionplans" = "FALSE"
    "Microsoft.Network/dnszones" = "TRUE"
    "Microsoft.Network/expressroutecircuits" = "FALSE"
    "Microsoft.Network/expressrouteports" = "FALSE"
    "Microsoft.Network/loadbalancers" = "TRUE"
    "Microsoft.Network/localnetworkgateways" = "TRUE"
    "Microsoft.Network/networkintentpolicies" = "TRUE"
    "Microsoft.Network/networkinterfaces" = "TRUE"
    "Microsoft.Network/networksecuritygroups" = "TRUE"
    "Microsoft.Network/networkwatchers" = "TRUE"
    "Microsoft.Network/networkwatchers/connectionmonitors" = "TRUE"
    "Microsoft.Network/networkwatchers/lenses" = "TRUE"
    "Microsoft.Network/networkwatchers/pingmeshes" = "TRUE"
    "Microsoft.Network/publicipaddresses" = "TRUE"
    "Microsoft.Network/publicipprefixes" = "TRUE"
    "Microsoft.Network/routefilters" = "FALSE"
    "Microsoft.Network/routetables" = "TRUE"
    "Microsoft.Network/trafficmanagerprofiles" = "TRUE"
    "Microsoft.Network/virtualnetworkgateways" = "TRUE"
    "Microsoft.Network/virtualnetworks" = "TRUE"
    "Microsoft.NotificationHubs/namespaces" = "TRUE"
    "Microsoft.NotificationHubs/namespaces/notificationhubs" = "TRUE"
    "Microsoft.OperationalInsights/workspaces" = "TRUE"
    "Microsoft.OperationsManagement/managementconfigurations" = "TRUE"
    "Microsoft.OperationsManagement/solutions" = "TRUE"
    "Microsoft.OperationsManagement/views" = "TRUE"
    "Microsoft.Portal/dashboards" = "TRUE"
    "Microsoft.PowerBI/workspacecollections" = "TRUE"
    "Microsoft.PowerBIDedicated/capacities" = "TRUE"
    "Microsoft.RecoveryServices/vaults" = "TRUE"
    "Microsoft.Relay/namespaces" = "TRUE"
    "Microsoft.SaaS/applications" = "FALSE"
    "Microsoft.Scheduler/flows" = "TRUE"
    "Microsoft.Scheduler/jobcollections" = "TRUE"
    "Microsoft.Search/searchservices" = "TRUE"
    "Microsoft.ServiceBus/namespaces" = "TRUE"
    "Microsoft.ServiceFabric/clusters" = "TRUE"
    "Microsoft.ServiceFabricMesh/applications" = "TRUE"
    "Microsoft.ServiceFabricMesh/networks" = "TRUE"
    "Microsoft.ServiceFabricMesh/volumes" = "TRUE"
    "Microsoft.SignalRService/signalr" = "TRUE"
    "Microsoft.SiteRecovery/siterecoveryvault" = "FALSE"
    "Microsoft.Solutions/appliancedefinitions" = "FALSE"
    "Microsoft.Solutions/appliances" = "FALSE"
    "Microsoft.Solutions/applicationdefinitions" = "FALSE"
    "Microsoft.Solutions/applications" = "FALSE"
    "Microsoft.Sql/servers" = "TRUE"
    "Microsoft.Sql/servers/databases" = "TRUE"
    "Microsoft.Sql/servers/elasticpools" = "TRUE"
    "Microsoft.Sql/virtualclusters" = "TRUE"
    "Microsoft.Storage/storageaccounts" = "TRUE"
    "Microsoft.StorageSync/storagesyncservices" = "TRUE"
    "Microsoft.StorSimple/managers" = "FALSE"
    "Microsoft.StreamAnalytics/streamingjobs" = "TRUE"
    "Microsoft.TimeSeriesInsights/environments" = "TRUE"
    "Microsoft.TimeSeriesInsights/environments/eventsources" = "TRUE"
    "Microsoft.TimeSeriesInsights/environments/referencedatasets" = "TRUE"
    "microsoft.visualstudio/account" = "TRUE"
    "microsoft.visualstudio/account/extension" = "TRUE"
    "microsoft.visualstudio/account/project" = "TRUE"
    "Microsoft.Web/certificates" = "TRUE"
    "Microsoft.Web/classicmobileservices" = "FALSE"
    "Microsoft.Web/connectiongateways" = "TRUE"
    "Microsoft.Web/connections" = "TRUE"
    "Microsoft.Web/customapis" = "TRUE"
    "Microsoft.Web/hostingenvironments" = "FALSE"
    "Microsoft.Web/serverfarms" = "TRUE"
    "Microsoft.Web/sites" = "TRUE"
    "Microsoft.Web/sites/premieraddons" = "TRUE"
    "Microsoft.Web/sites/slots" = "TRUE"
    "Microsoft.WindowsIoT/deviceservices" = "TRUE"
}



## Move Limitation Hash Table
$limitationList = @{
    "Microsoft.AnalysisServices/servers"  = "FALSE"
    "Microsoft.ApiManagement/service" = "FALSE"
    "Microsoft.Automation/automationaccounts" = "FALSE"
    "Microsoft.Automation/automationaccounts/configurations" = "FALSE"
    "Microsoft.Automation/automationaccounts/runbooks" = "FALSE"
    "Microsoft.AzureActiveDirectory/b2cdirectories" = "FALSE"
    "Microsoft.AzureStack/registrations" = "FALSE"
    "Microsoft.Batch/batchaccounts" = "FALSE"
    "Microsoft.BizTalkServices/biztalk" = "FALSE"
    "Microsoft.BotService/botservices" = "FALSE"
    "Microsoft.Cache/redis" = "FALSE"
    "Microsoft.Cdn/profiles" = "FALSE"
    "Microsoft.Cdn/profiles/endpoints" = "FALSE"
    "Microsoft.CertificateRegistration/certificateorders" = "FALSE"
    "Microsoft.CognitiveServices/accounts" = "FALSE"
    "Microsoft.Compute/virtualmachines/extensions" = "FALSE"
    "Microsoft.ContainerRegistry/registries" = "FALSE"
    "Microsoft.ContainerRegistry/registries/buildtasks" = "FALSE"
    "Microsoft.ContainerRegistry/registries/webhooks" = "FALSE"
    "Microsoft.ContentModerator/applications" = "FALSE"
    "Microsoft.CostManagement/connectors" = "FALSE"
    "Microsoft.CustomerInsights/hubs" = "FALSE"
    "Microsoft.DataCatalog/catalogs" = "FALSE"
    "Microsoft.DataFactory/datafactories" = "FALSE"
    "Microsoft.DataFactory/factories" = "FALSE"
    "Microsoft.DataLakeAnalytics/accounts" = "FALSE"
    "Microsoft.DataLakeStore/accounts" = "FALSE"
    "Microsoft.Devices/iothubs" = "FALSE"
    "Microsoft.Devices/provisioningservices" = "FALSE"
    "Microsoft.DevTestLab/labs/servicerunners" = "FALSE"
    "Microsoft.DocumentDB/databaseaccounts" = "FALSE"
    "Microsoft.DomainRegistration/domains" = "FALSE"
    "Microsoft.EventGrid/topics" = "FALSE"
    "Microsoft.EventHub/clusters" = "FALSE"
    "Microsoft.EventHub/namespaces" = "FALSE"
    "Microsoft.HanaOnAzure/hanainstances" = "FALSE"
    "Microsoft.HDInsight/clusters" = "TRUE - https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-move-resources#hdinsight-limitations"
    "Microsoft.ImportExport/jobs" = "FALSE"
    "microsoft.insights/actiongroups" = "FALSE"
    "microsoft.insights/alertrules" = "FALSE"
    "microsoft.insights/autoscalesettings" = "FALSE"
    "microsoft.insights/components" = "FALSE"
    "microsoft.insights/scheduledqueryrules" = "FALSE"
    "microsoft.insights/webtests" = "FALSE"
    "microsoft.insights/workbooks" = "FALSE"
    "Microsoft.IoTCentral/iotapps" = "FALSE"
    "Microsoft.KeyVault/vaults" = "FALSE"
    "Microsoft.LabServices/labaccounts" = "FALSE"
    "Microsoft.LocationBasedServices/accounts" = "FALSE"
    "Microsoft.LocationServices/accounts" = "FALSE"
    "Microsoft.Logic/integrationaccounts" = "FALSE"
    "Microsoft.Logic/workflows" = "FALSE"
    "Microsoft.MachineLearning/commitmentplans" = "FALSE"
    "Microsoft.MachineLearning/workspaces" = "FALSE"
    "Microsoft.MachineLearningCompute/operationalizationclusters" = "FALSE"
    "Microsoft.MachineLearningExperimentation/accounts" = "FALSE"
    "Microsoft.MachineLearningExperimentation/accounts/workspaces" = "FALSE"
    "Microsoft.MachineLearningExperimentation/accounts/workspaces/projects" = "FALSE"
    "Microsoft.MachineLearningExperimentation/teamaccounts" = "FALSE"
    "Microsoft.MachineLearningExperimentation/teamaccounts/workspaces" = "FALSE"
    "Microsoft.MachineLearningExperimentation/teamaccounts/workspaces/projects" = "FALSE"
    "Microsoft.MachineLearningModelManagement/accounts" = "FALSE"
    "Microsoft.ManagedIdentity/userassignedidentities" = "FALSE"
    "Microsoft.Maps/accounts" = "FALSE"
    "Microsoft.Media/mediaservices" = "FALSE"
    "Microsoft.Media/mediaservices/liveevents" = "FALSE"
    "Microsoft.Media/mediaservices/streamingendpoints" = "FALSE"
    "Microsoft.Network/applicationsecuritygroups" = "FALSE"
    "Microsoft.Network/connections" = "FALSE"
    "Microsoft.Network/dnszones" = "FALSE"
    "Microsoft.Network/loadbalancers" = "TRUE - Standard SKU Load Balancer can't be moved."
    "Microsoft.Network/localnetworkgateways" = "FALSE"
    "Microsoft.Network/networkintentpolicies" = "FALSE"
    "Microsoft.Network/networkinterfaces" = "FALSE"
    "Microsoft.Network/networksecuritygroups" = "FALSE"
    "Microsoft.Network/networkwatchers" = "FALSE"
    "Microsoft.Network/networkwatchers/connectionmonitors" = "FALSE"
    "Microsoft.Network/networkwatchers/lenses" = "FALSE"
    "Microsoft.Network/networkwatchers/pingmeshes" = "FALSE"
    "Microsoft.Network/publicipaddresses" = "TRUE - Standard SKU Public IP can't be moved."
    "Microsoft.Network/publicipprefixes" = "FALSE"
    "Microsoft.Network/routetables" = "FALSE"
    "Microsoft.Network/trafficmanagerprofiles" = "FALSE"
    "Microsoft.Network/virtualnetworkgateways" = "FALSE"
    "Microsoft.Network/virtualnetworks" = "TRUE - Unsupported if the vNet contains a subnet with resource navigation link."
    "Microsoft.NotificationHubs/namespaces" = "FALSE"
    "Microsoft.NotificationHubs/namespaces/notificationhubs" = "FALSE"
    "Microsoft.OperationalInsights/workspaces" = "FALSE"
    "Microsoft.OperationsManagement/managementconfigurations" = "FALSE"
    "Microsoft.OperationsManagement/solutions" = "FALSE"
    "Microsoft.OperationsManagement/views" = "FALSE"
    "Microsoft.Portal/dashboards" = "FALSE"
    "Microsoft.PowerBI/workspacecollections" = "FALSE"
    "Microsoft.PowerBIDedicated/capacities" = "FALSE"
    "Microsoft.RecoveryServices/vaults" = "TRUE - Recovery Services vault doesn't support cross subscription backups."
    "Microsoft.Relay/namespaces" = "FALSE"
    "Microsoft.Scheduler/flows" = "FALSE"
    "Microsoft.Scheduler/jobcollections" = "FALSE"
    "Microsoft.Search/searchservices" = "TRUE - You can't move multiple Search resources placed in different regions all at once."
    "Microsoft.ServiceBus/namespaces" = "FALSE"
    "Microsoft.ServiceFabric/clusters" = "FALSE"
    "Microsoft.ServiceFabricMesh/applications" = "FALSE"
    "Microsoft.ServiceFabricMesh/networks" = "FALSE"
    "Microsoft.ServiceFabricMesh/volumes" = "FALSE"
    "Microsoft.SignalRService/signalr" = "FALSE"
    "Microsoft.Sql/servers" = "FALSE"
    "Microsoft.Sql/servers/databases" = "FALSE"
    "Microsoft.Sql/servers/elasticpools" = "FALSE"
    "Microsoft.Sql/virtualclusters" = "FALSE"
    "Microsoft.Storage/storageaccounts" = "FALSE"
    "Microsoft.StorageSync/storagesyncservices" = "FALSE"
    "Microsoft.StreamAnalytics/streamingjobs" = "FALSE"
    "Microsoft.TimeSeriesInsights/environments" = "FALSE"
    "Microsoft.TimeSeriesInsights/environments/eventsources" = "FALSE"
    "Microsoft.TimeSeriesInsights/environments/referencedatasets" = "FALSE"
    "microsoft.visualstudio/account" = "FALSE"
    "microsoft.visualstudio/account/extension" = "FALSE"
    "microsoft.visualstudio/account/project" = "FALSE"
    "Microsoft.Web/certificates" = "FALSE"
    "Microsoft.Web/connectiongateways" = "FALSE"
    "Microsoft.Web/connections" = "FALSE"
    "Microsoft.Web/customapis" = "FALSE"
    "Microsoft.Web/serverfarms" = "FALSE"
    "Microsoft.Web/sites" = "TRUE - https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-move-resources#moving-across-subscriptions"
    "Microsoft.Web/sites/premieraddons" = "FALSE"
    "Microsoft.Web/sites/slots" = "FALSE"
    "Microsoft.WindowsIoT/deviceservices" = "FALSE"
}


#Set CSV Headers
"""Resource Name"",""Resource Group"",""Destination Resource Group"",""Resource Type"",""Move Supported"",""Limitations"",""Additional Notes""" | Out-File -Encoding ASCII -FilePath ".\csp_migration.csv"

foreach ($Resource in Get-AzResource) {

    #Check Hash Table for Move Support
    $support = $null
    $support = $supportList[$Resource.ResourceType]

    #Check Hash Table for Move Limitation
    $limitation = $null
    $limitation = $limitationList[$Resource.ResourceType]
    if($null -eq $limitation) {
        $limitation = "FALSE"
    }

    #Write Output for Resource to CSV
    """"+$Resource.Name+""","""+$Resource.ResourceGroupName+""","""+$Resource.ResourceGroupName+""","""+$Resource.ResourceType+""","""+$support+""","""+$limitation+"""" | 
    Out-File -Encoding ASCII -FilePath  ".\csp_migration.csv" -Append

}